import { Contract, BrowserProvider, JsonRpcSigner } from "ethers";
// deployment.json is generated by `pnpm sync:abi` and baked into the bundle.
import deployment from "../generated/deployment.json";

// ── Addresses ──────────────────────────────────────────────────────────────

export const CHAIN_ID              = deployment.chainId;
export const FACTORY_ADDRESS       = deployment.GymFinderFactory.address;
export const LOYALTY_TOKEN_ADDRESS = deployment.LoyaltyToken.address;
export const SPLITTER_ADDRESS      = deployment.PaymentSplitter.address;
export const DEMO_GYM_ADDRESS      = (deployment as Record<string, unknown>).demoGymBranch as string | undefined;

// ── ABIs (typed via JSON import) ───────────────────────────────────────────

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const FACTORY_ABI        = deployment.GymFinderFactory.abi  as any[];
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const LOYALTY_TOKEN_ABI  = deployment.LoyaltyToken.abi       as any[];
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const SPLITTER_ABI       = deployment.PaymentSplitter.abi    as any[];
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const GYM_BRANCH_ABI     = (deployment as Record<string, unknown>).GymBranch as { abi: any[] };
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const SHOP_PRODUCT_ABI   = (deployment as Record<string, unknown>).ShopProduct as { abi: any[] };

// ── Etherscan helper ───────────────────────────────────────────────────────

export const ETHERSCAN_BASE =
  deployment.chainId === 11155111
    ? "https://sepolia.etherscan.io"
    : deployment.chainId === 1
    ? "https://etherscan.io"
    : null;

// ── Contract factories ─────────────────────────────────────────────────────

type Provider = BrowserProvider;
type Signer   = JsonRpcSigner;
type PS       = Provider | Signer;

export function getFactory(ps: PS) {
  return new Contract(FACTORY_ADDRESS, FACTORY_ABI, ps);
}

export function getLoyaltyToken(ps: PS) {
  return new Contract(LOYALTY_TOKEN_ADDRESS, LOYALTY_TOKEN_ABI, ps);
}

export function getSplitter(ps: PS) {
  return new Contract(SPLITTER_ADDRESS, SPLITTER_ABI, ps);
}

export function getGymBranch(address: string, ps: PS) {
  return new Contract(address, GYM_BRANCH_ABI.abi, ps);
}

export function getShopProduct(address: string, ps: PS) {
  return new Contract(address, SHOP_PRODUCT_ABI.abi, ps);
}

// ── Data types returned by contract calls ─────────────────────────────────

export interface GymInfo {
  address:        string;
  name:           string;
  owner:          string;
  isActive:       boolean;
  subscriptionOk: boolean;
  monthlyFee:     bigint;
  pointsPerVisit: bigint;
  shopProduct:    string;
}

export interface ProductInfo {
  id:               number;
  name:             string;
  description:      string;
  loyaltyPointCost: bigint;
  productType:      number; // 0=PHYSICAL 1=SERVICE 2=DISCOUNT
  stock:            bigint;
  isActive:         boolean;
}

export const PRODUCT_TYPE_LABEL: Record<number, string> = {
  0: "Physical",
  1: "Service",
  2: "Discount",
};

// ── Composite reads ────────────────────────────────────────────────────────

export async function readGymInfo(address: string, provider: BrowserProvider): Promise<GymInfo> {
  const c = getGymBranch(address, provider);
  const [name, owner, isActive, subOk, fee, rate, shop] = await Promise.all([
    c.gymName() as Promise<string>,
    c.owner()   as Promise<string>,
    c.isActive() as Promise<boolean>,
    c.checkSubscriptionStatus() as Promise<boolean>,
    c.monthlySubscriptionFee()  as Promise<bigint>,
    c.loyaltyPointsPerVisit()   as Promise<bigint>,
    c.shopProduct()             as Promise<string>,
  ]);
  return {
    address,
    name,
    owner,
    isActive,
    subscriptionOk: subOk,
    monthlyFee:     fee,
    pointsPerVisit: rate,
    shopProduct:    shop,
  };
}

export async function readProducts(
  shopAddress: string,
  provider: BrowserProvider
): Promise<ProductInfo[]> {
  const shop = getShopProduct(shopAddress, provider);
  const count = Number(await shop.nextProductId() as bigint);
  if (count === 0) return [];

  const results: ProductInfo[] = [];
  for (let i = 0; i < count; i++) {
    const p = await shop.getProduct(i) as {
      name:             string;
      description:      string;
      loyaltyPointCost: bigint;
      productType:      bigint;
      stock:            bigint;
      isActive:         boolean;
    };
    results.push({
      id:               i,
      name:             p.name,
      description:      p.description,
      loyaltyPointCost: p.loyaltyPointCost,
      productType:      Number(p.productType),
      stock:            p.stock,
      isActive:         p.isActive,
    });
  }
  return results;
}

export async function readLoyaltyBalance(
  address: string,
  provider: BrowserProvider
): Promise<bigint> {
  const lt = getLoyaltyToken(provider);
  return lt.balanceOf(address) as Promise<bigint>;
}

export async function readAllGyms(provider: BrowserProvider): Promise<string[]> {
  const f = getFactory(provider);
  return f.getRegisteredGyms() as Promise<string[]>;
}

export async function readFactoryOwner(provider: BrowserProvider): Promise<string> {
  const f = getFactory(provider);
  return f.owner() as Promise<string>;
}

export async function readPlatformFeePercent(provider: BrowserProvider): Promise<bigint> {
  const f = getFactory(provider);
  return f.platformFeePercent() as Promise<bigint>;
}

export async function readAccumulatedTreasuryFees(provider: BrowserProvider): Promise<bigint> {
  const s = getSplitter(provider);
  return s.accumulatedTreasuryFees() as Promise<bigint>;
}

export async function readGymOwnerFees(
  ownerAddress: string,
  provider: BrowserProvider
): Promise<bigint> {
  const s = getSplitter(provider);
  return s.getAccumulatedFees(ownerAddress) as Promise<bigint>;
}
